### PR TITLE
Add option to override resource-quota defaults per namespace

### PR DESCRIPTION
**Pull request by glrf**
## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog

### CODE REVIEW

**Comment by glrf** [comment]
I did not manage to parse a string containing JSON in JMESPath, so here is a proposal using an annotation per resource.

Documentation is very sparse. I will add detailed documentation to `appuio-io-docs`.

**Review by bastjan — APPROVED** [review]
LGTM with a little more documentation in `appuio-io-docs`.

**Review by simu — APPROVED** [review]
LGTM. 

The only potential problem I see is that the current implementation doesn't allow adding quotas for fields which aren't specified by the component by adding an annotation on a namespace. However in that case, a separate quota object can be created anyway I think.

**Comment by glrf** [comment]
> LGTM.
> 
> The only potential problem I see is that the current implementation doesn't allow adding quotas for fields which aren't specified by the component by adding an annotation on a namespace. However in that case, a separate quota object can be created anyway I think.

Yep, I also don't really like that we cannot add quota for additional fields, but I did not find a way to make this work.

**Pull request merged**
